[package]
name = "lang-explorer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.82"
burn = { version = "0.13.2", features = ["cuda"] }
cc = "1.1.20"
clap = { version = "4.5.17", features = ["derive"] }
libloading = "0.8.5"
mpi = "0.8.0"
